apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-tools
  annotations:
<<<<<<< HEAD
#    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
=======
    kubernetes.io/ingress.class: "contour"
spec:
  ingressClassName: contour
>>>>>>> origin/main
  rules:
  - host: jenkins-master.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-service
            port:
              number: 8080
